version: '3.7'
services:
    postgres:
        image: postgres
        environment:
          - POSTGRES_USER=${PGUSER}
          - POSTGRES_PASSWORD=${PGPASSWORD}
        ports:
          - 5432:5432
        volumes:
          - ./scripts/full.sql:/docker-entrypoint-initdb.d/full.sql          
    web-node:
        container_name: web-node-backend
        build: .
        ports:
          - 8080:8080
        volumes:
          - .:/usr/src/app
          - /usr/src/app/node_modules
        depends_on:
          - postgres
        restart: always
